# Generated by Django 2.0 on 2017-12-18 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('excluded_item_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('record_keeping', models.BooleanField(default=False)),
                ('karma_exclude', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedditAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('reddit_user_name', models.CharField(max_length=150)),
                ('reddit_token', models.CharField(max_length=150)),
                ('authorized_date', models.DateField(auto_now=True)),
                ('schedule', models.CharField(choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='None', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('reddit_user_name', models.CharField(max_length=150)),
                ('sub_comment_id', models.CharField(max_length=20)),
                ('sub_comment_body', models.CharField(max_length=1000)),
                ('sub_comment_status', models.CharField(max_length=20)),
                ('op_run_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
